### PR TITLE
Add unattended-upgrades

### PR DESCRIPTION
**Pull request by mbologna**
Install and configure unattended-upgrades

### CODE REVIEW

**Comment by moio** [comment]
I am not sure I really want this for uptime reasons. Need to think a bit, please don't worry if this PR stays around for a while!

**Comment by moio** [comment]
I rebased the patches, removed Postfix and installed them on my pi. Let's wait for some days and if it works as expected, I will merge this.

**Comment by mbologna** [comment]
Check this path: `/var/log/unattended-upgrades`

**Comment by moio** [comment]
There is probably something I do not understand fully, as some updates seem to be retained a bit. In any case, this is a step in the right direction so I merged it. Thanks!

**Pull request merged**
